// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "localhost",
    "basePath": ":6006",
    "paths": {
        "/api/v1/admin/accounts": {
            "get": {
                "description": "Xem danh sách account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "Xem danh sách account",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "description": "Tạo mới account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "Tạo mới account",
                "parameters": [
                    {
                        "description": "name platform link",
                        "name": "AccountForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.Account"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/admin/accounts/{account_id}": {
            "get": {
                "description": "Xem chi tiết account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "Xem chi tiết account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "account_id",
                        "name": "account_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "Xóa account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "Xóa account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "account_id",
                        "name": "account_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/admin/logs": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "monitor"
                ],
                "summary": "Lấy danh sách bản ghi log",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/collections.LogRecord"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/admin/profile": {
            "get": {
                "description": "do ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "lấy thông tin profile đang login",
                "responses": {}
            }
        },
        "/api/v1/admin/provinces": {
            "get": {
                "description": "do ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "lấy danh sách tỉnh thành",
                "responses": {}
            }
        },
        "/api/v1/admin/provinces/{{province_id}}": {
            "get": {
                "description": "do ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "lấy thông tin chi tiết của tỉnh thành",
                "responses": {}
            },
            "post": {
                "description": "do ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "cập nhật thông tin tỉnh thành",
                "responses": {}
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Đăng nhập hệ thôống CMS, lấy về access_token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Đăng nhập CMS",
                "parameters": [
                    {
                        "description": "username password",
                        "name": "LoginForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.Account"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Tạo tài khoản mới",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Đăng ký tài khoản",
                "parameters": [
                    {
                        "description": "username password",
                        "name": "RegisterForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterAccount"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/common/categories": {
            "get": {
                "description": "Xem danh sách Category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Xem danh sách Category",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "description": "Tạo mới Category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Tạo mới Category",
                "parameters": [
                    {
                        "description": "Name",
                        "name": "AccountForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.Category"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/common/categories/{category_id}": {
            "get": {
                "description": "Xem chi tiết Category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Xem chi tiết Category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "category_id",
                        "name": "category_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "put": {
                "description": "Cập nhật Category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Cập nhật Category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the Category",
                        "name": "category_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin cập nhật của Category",
                        "name": "CategoryForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.Category"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "Xóa Category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Xóa Category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "category_id",
                        "name": "category_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/common/keywords": {
            "get": {
                "description": "Xem danh sách Keyword",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Keyword"
                ],
                "summary": "Xem danh sách Keyword",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "description": "Tạo mới Keyword",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Keyword"
                ],
                "summary": "Tạo mới Keyword",
                "parameters": [
                    {
                        "description": "Name",
                        "name": "AccountForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.Keyword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/common/keywords/{keyword_id}": {
            "get": {
                "description": "Xem chi tiết Keyword",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Keyword"
                ],
                "summary": "Xem chi tiết Keyword",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Keyword_id",
                        "name": "keyword_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "put": {
                "description": "Sửa Keyword",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Keyword"
                ],
                "summary": "Update Keyword",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Keyword_id",
                        "name": "keyword_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin cập nhật của Keyword",
                        "name": "KeywordForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.Keyword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "Xóa Keyword",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Keyword"
                ],
                "summary": "Xóa Keyword",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Keyword_id",
                        "name": "keyword_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/common/labels": {
            "get": {
                "description": "Xem danh sách Label",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Label"
                ],
                "summary": "Xem danh sách Label",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "description": "Tạo mới Label",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Label"
                ],
                "summary": "Tạo mới Label",
                "parameters": [
                    {
                        "description": "name",
                        "name": "LabelForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.Label"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/common/labels/{label_id}": {
            "get": {
                "description": "Xem chi tiết Label",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Label"
                ],
                "summary": "Xem chi tiết Label",
                "parameters": [
                    {
                        "type": "string",
                        "description": "label_id",
                        "name": "label_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "put": {
                "description": "Sửa Label",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Label"
                ],
                "summary": "Update Label",
                "parameters": [
                    {
                        "type": "string",
                        "description": "label_id",
                        "name": "label_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin cập nhật của Label",
                        "name": "LabelForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.Label"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "Xóa Label",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Label"
                ],
                "summary": "Xóa Label",
                "parameters": [
                    {
                        "type": "string",
                        "description": "label_id",
                        "name": "label_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/common/linkNexts": {
            "get": {
                "description": "Xem danh sách LinkNext",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LinkNext"
                ],
                "summary": "Xem danh sách LinkNext",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "description": "Tạo mới LinkNext",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LinkNext"
                ],
                "summary": "Tạo mới LinkNext",
                "parameters": [
                    {
                        "description": "Name",
                        "name": "LinkNextForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.LinkNext"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/common/linkNexts/{linkNext_id}": {
            "get": {
                "description": "Xem chi tiết LinkNext",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LinkNext"
                ],
                "summary": "Xem chi tiết LinkNext",
                "parameters": [
                    {
                        "type": "string",
                        "description": "linkNext_id",
                        "name": "linkNext_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "put": {
                "description": "Cập nhật LinkNext",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LinkNext"
                ],
                "summary": "Cập nhật LinkNext",
                "parameters": [
                    {
                        "type": "string",
                        "description": "linkNext_id của LinkNext cần cập nhật",
                        "name": "linkNext_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin cập nhật của LinkNext",
                        "name": "LinkNextForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.LinkNext"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "Xóa LinkNext",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LinkNext"
                ],
                "summary": "Xóa LinkNext",
                "parameters": [
                    {
                        "type": "string",
                        "description": "linkNext_id",
                        "name": "linkNext_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/common/mentions": {
            "get": {
                "description": "Xem danh sách Mention",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mention"
                ],
                "summary": "Xem danh sách Mention",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/common/mentions/addLabel": {
            "get": {
                "description": "Xem danh sách Mention chưa gán nhãn",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mention"
                ],
                "summary": "Xem danh sách Mention chưa gán nhãn",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/common/mentions/addLabelFace": {
            "get": {
                "description": "Xem danh sách Mention chưa gán nhãn",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mention"
                ],
                "summary": "Xem danh sách Mention Face chưa gán nhãn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account ID",
                        "name": "account_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/common/mentions/addLabelWeb": {
            "get": {
                "description": "Xem danh sách Mention chưa gán nhãn",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mention"
                ],
                "summary": "Xem danh sách Mention Web chưa gán nhãn",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/common/mentions/countLabel": {
            "get": {
                "description": "Đếm label của Mention",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mention"
                ],
                "summary": "Đếm label của Mention",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/common/mentions/countLabelId": {
            "get": {
                "description": "Xem danh sách Mention",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mention"
                ],
                "summary": "Đếm danh sách Mention đã gán",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/common/mentions/{mention_id}": {
            "get": {
                "description": "Xem chi tiết Mention",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mention"
                ],
                "summary": "Xem chi tiết Mention",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mention_id",
                        "name": "mention_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "Xóa Mention",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mention"
                ],
                "summary": "Xóa Mention",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mention_id",
                        "name": "mention_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/common/mentions/{mention_id}/assign-label": {
            "put": {
                "description": "Gán nhãn cho Mention",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mention"
                ],
                "summary": "Gán nhãn cho Mention",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the Mention",
                        "name": "mention_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name of the Label to assign",
                        "name": "label_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/common/mentions/{mention_id}/assign-label-sentences": {
            "put": {
                "description": "Gán nhãn cho Sentences",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mention"
                ],
                "summary": "Gán nhãn cho Sentences",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the Mention",
                        "name": "mention_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Index of the sentence in the Sentences array",
                        "name": "sentence_index",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name of the Label to assign",
                        "name": "label_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/common/sources": {
            "get": {
                "description": "Xem danh sách Source",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Source"
                ],
                "summary": "Xem danh sách Source",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "description": "Tạo mới Source",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Source"
                ],
                "summary": "Tạo mới Source",
                "parameters": [
                    {
                        "description": "name",
                        "name": "AccountForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.Source"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/common/sources/type": {
            "get": {
                "description": "Xem danh sách Source theo nguồn",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Source"
                ],
                "summary": "Xem danh sách Source theo nguồn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Type Source",
                        "name": "typeSource",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/common/sources/{source_id}": {
            "get": {
                "description": "Xem chi tiết Source",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Source"
                ],
                "summary": "Xem chi tiết Source",
                "parameters": [
                    {
                        "type": "string",
                        "description": "source_id",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "put": {
                "description": "Cập nhật Source",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Source"
                ],
                "summary": "Cập nhật Source",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the SOurce",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin cập nhật của Source",
                        "name": "SourceForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.Source"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "Xóa Source",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Source"
                ],
                "summary": "Xóa Source",
                "parameters": [
                    {
                        "type": "string",
                        "description": "source_id",
                        "name": "source_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "admin.Account": {
            "type": "object",
            "properties": {
                "link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                }
            }
        },
        "admin.Category": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "admin.Keyword": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "admin.Label": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "admin.LinkNext": {
            "type": "object",
            "properties": {
                "box_element": {
                    "type": "string"
                },
                "category_element": {
                    "type": "string"
                },
                "check_category": {
                    "type": "string"
                },
                "check_desc": {
                    "type": "string"
                },
                "check_time": {
                    "type": "string"
                },
                "content_element": {
                    "type": "string"
                },
                "description_element": {
                    "type": "string"
                },
                "link_element": {
                    "type": "string"
                },
                "time_element": {
                    "type": "string"
                },
                "title_element": {
                    "type": "string"
                },
                "url_start": {
                    "type": "string"
                }
            }
        },
        "admin.Source": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "record": {
                    "$ref": "#/definitions/admin.SourceRecord"
                },
                "typeSource": {
                    "type": "string"
                },
                "url_start": {
                    "type": "string"
                }
            }
        },
        "admin.SourceRecord": {
            "type": "object",
            "properties": {
                "blocked": {
                    "type": "boolean"
                }
            }
        },
        "auth.Account": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "remember": {
                    "type": "boolean"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.LoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object",
                    "properties": {
                        "access_token": {
                            "type": "string"
                        },
                        "expire": {
                            "type": "string"
                        }
                    }
                },
                "message": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "auth.RegisterAccount": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "collections.LogRecord": {
            "type": "object",
            "properties": {
                "content_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "latency": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "prefer_url": {
                    "type": "string"
                },
                "request": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                },
                "user_agent": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
